name: Job Monitor

on:

  # Run every hour
  schedule:
    - cron: "0 * * * *"

  # Allows you to run it manually
  workflow_dispatch:
   inputs:
    test_url:
      description: "Job URL to test (leave empty for normal monitoring)"
      required: false
      type: string

permissions:
  contents: write

jobs:

  monitor:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt



      - name: Run job monitor
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          TEST_URL: ${{ github.event.inputs.test_url }}
        run: |
          python scraper.py

      # Save jobs.db permanently in the repository
      - name: Save database
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add jobs.db

          if git diff --cached --quiet; then
            echo "No database changes."
          else
            git commit -m "Update job monitor database"
            git push
          fi
